export interface ArtStyle {
  id: string;
  name: string;
  description: string;
  prompt: string;
  category: StyleCategory;
  preview: string;
  popular?: boolean;
  new?: boolean;
}

export type StyleCategory = 
  | "classic"
  | "modern"
  | "fantasy"
  | "cartoon"
  | "seasonal"
  | "artistic"
  | "profession"
  | "sports"
  | "cultural";

export const styleCategories: Record<StyleCategory, { name: string; description: string }> = {
  classic: {
    name: "Classic & Royal",
    description: "Timeless elegance and regal portraits",
  },
  modern: {
    name: "Modern Art",
    description: "Contemporary artistic styles",
  },
  fantasy: {
    name: "Fantasy & Adventure",
    description: "Magical and adventurous themes",
  },
  cartoon: {
    name: "Cartoon & Animation",
    description: "Fun animated and cartoon styles",
  },
  seasonal: {
    name: "Seasonal & Holiday",
    description: "Festive and seasonal themes",
  },
  artistic: {
    name: "Fine Art Styles",
    description: "Inspired by famous artists and movements",
  },
  profession: {
    name: "Professions & Jobs",
    description: "Your pet in various careers",
  },
  sports: {
    name: "Sports & Activities",
    description: "Athletic and action-packed styles",
  },
  cultural: {
    name: "Cultural & World",
    description: "Styles from around the globe",
  },
};

export const artStyles: ArtStyle[] = [
  // Classic & Royal (8 styles)
  {
    id: "royal-portrait",
    name: "Royal Portrait",
    description: "Transform your pet into Renaissance royalty",
    prompt: "A majestic royal portrait of a pet wearing ornate royal clothing with a golden crown, Renaissance oil painting style, regal pose, rich colors, detailed fabric textures, palace background with red velvet curtains",
    category: "classic",
    preview: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
    popular: true,
  },
  {
    id: "military-general",
    name: "Military General",
    description: "Noble military commander with medals",
    prompt: "Distinguished military portrait of a pet as a decorated general, wearing military uniform with gold epaulettes and medals, formal pose, classical oil painting style, dignified expression",
    category: "classic",
    preview: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400",
  },
  {
    id: "victorian-noble",
    name: "Victorian Noble",
    description: "Elegant Victorian era aristocrat",
    prompt: "Victorian era portrait of a pet as an English noble, wearing formal Victorian attire with high collar, monocle, distinguished pose, sepia-toned classical painting style",
    category: "classic",
    preview: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400",
  },
  {
    id: "queen-elizabeth",
    name: "Royal Queen",
    description: "Majestic queen with crown and jewels",
    prompt: "Regal portrait of a pet as a queen, wearing elaborate royal gown and diamond tiara, holding scepter, throne room background, classic oil painting, baroque style",
    category: "classic",
    preview: "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400",
  },
  {
    id: "duke-lord",
    name: "Duke/Lord",
    description: "Distinguished aristocratic nobleman",
    prompt: "Noble portrait of a pet as a duke or lord, wearing fancy coat with cravat, sitting in leather armchair, library background with books, classical portrait style",
    category: "classic",
    preview: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=400",
  },
  {
    id: "napoleonic",
    name: "Napoleonic Era",
    description: "Napoleon-style military leader",
    prompt: "Napoleonic portrait of a pet as emperor, bicorn hat, ornate military jacket with medals, dramatic pose on horseback, epic battle scene background, neoclassical style",
    category: "classic",
    preview: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400",
  },
  {
    id: "renaissance-merchant",
    name: "Renaissance Merchant",
    description: "Wealthy Renaissance trader",
    prompt: "Renaissance portrait of a pet as wealthy merchant, fine silk robes, gold jewelry, counting coins at desk, Flemish painting style, warm candlelight",
    category: "classic",
    preview: "https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=400",
  },
  {
    id: "baroque-royal",
    name: "Baroque Royal",
    description: "Dramatic baroque court portrait",
    prompt: "Baroque style royal portrait of a pet, dramatic lighting, velvet and gold clothing, ornate frame effect, Rembrandt-inspired chiaroscuro, opulent palace setting",
    category: "classic",
    preview: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
    new: true,
  },

  // Modern Art (8 styles)
  {
    id: "pop-art",
    name: "Pop Art",
    description: "Andy Warhol inspired vibrant pop art",
    prompt: "Bold pop art portrait of a pet in Andy Warhol style, vibrant contrasting colors, halftone dots, comic book aesthetic, high contrast, four panel style",
    category: "modern",
    preview: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400",
    popular: true,
  },
  {
    id: "minimalist",
    name: "Minimalist",
    description: "Clean, simple line art portrait",
    prompt: "Minimalist portrait of a pet, single continuous line drawing, clean white background, simple elegant strokes, modern art gallery style",
    category: "modern",
    preview: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
  },
  {
    id: "geometric",
    name: "Geometric",
    description: "Low-poly geometric art style",
    prompt: "Geometric low-poly portrait of a pet, triangular facets, vibrant gradient colors, modern digital art style, sharp edges, crystalline appearance",
    category: "modern",
    preview: "https://images.unsplash.com/photo-1544568100-847a948585b9?w=400",
    new: true,
  },
  {
    id: "neon-glow",
    name: "Neon Glow",
    description: "Vibrant neon light effects",
    prompt: "Neon portrait of a pet, glowing neon outlines, cyberpunk aesthetic, dark background with bright neon colors, synthwave style, futuristic look",
    category: "modern",
    preview: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=400",
    popular: true,
  },
  {
    id: "graffiti",
    name: "Street Graffiti",
    description: "Urban street art style",
    prompt: "Graffiti art portrait of a pet, spray paint style, brick wall background, bold colors, street art aesthetic, urban hip hop culture",
    category: "modern",
    preview: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=400",
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    description: "Retro 80s aesthetic",
    prompt: "Vaporwave portrait of a pet, pink and blue gradients, retro grid background, palm trees, sunset, glitch effects, 80s aesthetic",
    category: "modern",
    preview: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=400",
  },
  {
    id: "abstract-cubism",
    name: "Abstract Cubism",
    description: "Picasso-style cubist art",
    prompt: "Cubist portrait of a pet in Picasso style, fragmented geometric shapes, multiple perspectives, bold colors, abstract modern art",
    category: "modern",
    preview: "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=400",
  },
  {
    id: "digital-glitch",
    name: "Digital Glitch",
    description: "Glitchy digital art effect",
    prompt: "Glitch art portrait of a pet, pixel distortion, RGB color separation, scan lines, corrupted data aesthetic, cyberpunk style",
    category: "modern",
    preview: "https://images.unsplash.com/photo-1534361960057-19889db9621e?w=400",
  },

  // Cartoon & Animation (10 styles)
  {
    id: "disney-pixar",
    name: "Disney/Pixar",
    description: "Adorable 3D animated movie style",
    prompt: "3D animated portrait of a pet in Disney Pixar animation style, big expressive eyes, soft fur texture, warm lighting, heartwarming expression, movie poster quality",
    category: "cartoon",
    preview: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=400",
    popular: true,
  },
  {
    id: "anime",
    name: "Anime/Manga",
    description: "Japanese anime art style",
    prompt: "Anime style portrait of a pet, large sparkling eyes, kawaii expression, soft pastel colors, manga illustration style, cherry blossom background",
    category: "cartoon",
    preview: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=400",
    popular: true,
  },
  {
    id: "cartoon-classic",
    name: "Classic Cartoon",
    description: "Vintage cartoon character style",
    prompt: "Classic cartoon portrait of a pet in vintage animation style, bold outlines, expressive face, retro color palette, 1950s cartoon aesthetic",
    category: "cartoon",
    preview: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=400",
  },
  {
    id: "chibi",
    name: "Chibi Style",
    description: "Cute oversized head anime style",
    prompt: "Chibi style portrait of a pet, oversized cute head, tiny body, big sparkly eyes, kawaii aesthetic, pastel background, adorable expression",
    category: "cartoon",
    preview: "https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=400",
  },
  {
    id: "studio-ghibli",
    name: "Studio Ghibli",
    description: "Miyazaki-inspired animation",
    prompt: "Studio Ghibli style portrait of a pet, soft watercolor look, whimsical magical atmosphere, lush nature background, Hayao Miyazaki aesthetic",
    category: "cartoon",
    preview: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
    popular: true,
  },
  {
    id: "simpsons",
    name: "Simpsons Style",
    description: "Yellow cartoon family style",
    prompt: "The Simpsons style portrait of a pet, yellow skin tone, overbite, Matt Groening art style, Springfield background, classic cartoon",
    category: "cartoon",
    preview: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400",
  },
  {
    id: "south-park",
    name: "South Park",
    description: "Paper cutout animation style",
    prompt: "South Park style portrait of a pet, simple paper cutout look, construction paper aesthetic, flat colors, bold outlines",
    category: "cartoon",
    preview: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400",
  },
  {
    id: "rick-morty",
    name: "Rick and Morty",
    description: "Adult Swim cartoon style",
    prompt: "Rick and Morty style portrait of a pet, squiggly lines, pastel colors, interdimensional background, Adult Swim aesthetic",
    category: "cartoon",
    preview: "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400",
  },
  {
    id: "pokemon",
    name: "Pokemon Style",
    description: "Turn your pet into a Pokemon",
    prompt: "Pokemon style portrait of a pet as a new Pokemon creature, Ken Sugimori art style, dynamic pose, elemental effects, game card aesthetic",
    category: "cartoon",
    preview: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=400",
    new: true,
  },
  {
    id: "comic-book",
    name: "Comic Book Hero",
    description: "Marvel/DC comic style",
    prompt: "Comic book style portrait of a pet, bold ink lines, halftone dots, dynamic action pose, speech bubble, superhero comic aesthetic",
    category: "cartoon",
    preview: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400",
  },

  // Fine Art Styles (10 styles)
  {
    id: "oil-painting",
    name: "Oil Painting",
    description: "Classical oil painting technique",
    prompt: "Classical oil painting portrait of a pet, rich textured brushstrokes, dramatic lighting, warm earth tones, museum quality, Renaissance painting technique",
    category: "artistic",
    preview: "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400",
    popular: true,
  },
  {
    id: "watercolor",
    name: "Watercolor",
    description: "Soft, flowing watercolor painting",
    prompt: "Delicate watercolor portrait of a pet, soft color washes, wet-on-wet technique, flowing paint edges, artistic splashes, dreamy pastel palette",
    category: "artistic",
    preview: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=400",
  },
  {
    id: "van-gogh",
    name: "Van Gogh Style",
    description: "Swirling brushstrokes like Starry Night",
    prompt: "Portrait of a pet in Vincent van Gogh style, swirling expressive brushstrokes, vibrant colors, thick impasto technique, starry night background, post-impressionist",
    category: "artistic",
    preview: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400",
    popular: true,
  },
  {
    id: "impressionist",
    name: "Impressionist",
    description: "Monet-inspired soft impressionism",
    prompt: "Impressionist portrait of a pet, soft dappled light, loose brushwork, garden setting with flowers, Monet-inspired color palette, atmospheric quality",
    category: "artistic",
    preview: "https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=400",
  },
  {
    id: "sketch",
    name: "Pencil Sketch",
    description: "Detailed graphite pencil drawing",
    prompt: "Detailed pencil sketch of a pet, realistic graphite drawing, fine shading and hatching, textured paper background, artist study quality",
    category: "artistic",
    preview: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
  },
  {
    id: "stained-glass",
    name: "Stained Glass",
    description: "Medieval stained glass window",
    prompt: "Stained glass window art of a pet, vibrant jewel-toned colors, black lead outlines, cathedral light effect, Art Nouveau influence, glowing translucent appearance",
    category: "artistic",
    preview: "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=400",
    new: true,
  },
  {
    id: "acrylic-pour",
    name: "Acrylic Pour",
    description: "Fluid acrylic art style",
    prompt: "Acrylic pour art portrait of a pet, swirling fluid colors, organic cell patterns, vibrant color mixing, abstract background, modern art technique",
    category: "artistic",
    preview: "https://images.unsplash.com/photo-1534361960057-19889db9621e?w=400",
  },
  {
    id: "charcoal",
    name: "Charcoal Drawing",
    description: "Dramatic charcoal portrait",
    prompt: "Charcoal drawing portrait of a pet, dramatic black and white, rich shadows, expressive strokes, textured paper, fine art quality",
    category: "artistic",
    preview: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400",
  },
  {
    id: "art-deco",
    name: "Art Deco",
    description: "1920s geometric elegance",
    prompt: "Art Deco portrait of a pet, geometric patterns, gold and black colors, 1920s aesthetic, elegant lines, Gatsby era styling",
    category: "artistic",
    preview: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
  },
  {
    id: "pointillism",
    name: "Pointillism",
    description: "Seurat-style dot painting",
    prompt: "Pointillist portrait of a pet, composed of small colored dots, Georges Seurat style, vibrant optical color mixing, neo-impressionist technique",
    category: "artistic",
    preview: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400",
  },

  // Fantasy & Adventure (8 styles)
  {
    id: "wizard",
    name: "Wizard",
    description: "Mystical wizard with magic powers",
    prompt: "Fantasy portrait of a pet as a powerful wizard, wearing wizard robes and hat, magical staff, glowing spell effects, mystical library background, enchanted atmosphere",
    category: "fantasy",
    preview: "https://images.unsplash.com/photo-1534361960057-19889db9621e?w=400",
    popular: true,
  },
  {
    id: "knight",
    name: "Medieval Knight",
    description: "Brave knight in shining armor",
    prompt: "Medieval portrait of a pet as a noble knight, wearing gleaming plate armor, sword and shield, castle background, heroic pose, dramatic lighting",
    category: "fantasy",
    preview: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400",
  },
  {
    id: "fairy",
    name: "Fairy Tale",
    description: "Enchanted fairy tale character",
    prompt: "Magical fairy tale portrait of a pet with delicate fairy wings, surrounded by sparkles and flowers, enchanted forest background, dreamy soft lighting",
    category: "fantasy",
    preview: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
  },
  {
    id: "space-explorer",
    name: "Space Explorer",
    description: "Astronaut exploring the galaxy",
    prompt: "Sci-fi portrait of a pet as an astronaut, wearing detailed space suit, floating in space, Earth in background, stars and nebulae, cinematic lighting",
    category: "fantasy",
    preview: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400",
    new: true,
  },
  {
    id: "superhero",
    name: "Superhero",
    description: "Caped crusader saving the day",
    prompt: "Comic book style portrait of a pet as a superhero, wearing cape and mask, dynamic action pose, city skyline background, dramatic lighting, comic panel style",
    category: "fantasy",
    preview: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400",
  },
  {
    id: "dragon-rider",
    name: "Dragon Rider",
    description: "Epic fantasy dragon companion",
    prompt: "Fantasy portrait of a pet as dragon rider, flying on dragon back, epic mountain landscape, dramatic clouds, fantasy game art style",
    category: "fantasy",
    preview: "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400",
  },
  {
    id: "viking-warrior",
    name: "Viking Warrior",
    description: "Norse warrior with battle gear",
    prompt: "Viking portrait of a pet as fierce warrior, horned helmet, battle axe, fur cloak, longship background, Norse mythology aesthetic",
    category: "fantasy",
    preview: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=400",
  },
  {
    id: "pirate-captain",
    name: "Pirate Captain",
    description: "Swashbuckling sea captain",
    prompt: "Pirate portrait of a pet as ship captain, tricorn hat, eye patch, treasure map, pirate ship background, Caribbean adventure style",
    category: "fantasy",
    preview: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400",
  },

  // Seasonal & Holiday (8 styles)
  {
    id: "christmas",
    name: "Christmas",
    description: "Festive holiday portrait",
    prompt: "Cozy Christmas portrait of a pet, wearing Santa hat, surrounded by presents and Christmas tree, warm fireplace glow, snow falling outside window, festive atmosphere",
    category: "seasonal",
    preview: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400",
    popular: true,
  },
  {
    id: "halloween",
    name: "Halloween",
    description: "Spooky Halloween costume",
    prompt: "Fun Halloween portrait of a pet, vampire or witch costume, pumpkins and bats, full moon background, spooky but cute atmosphere, purple and orange lighting",
    category: "seasonal",
    preview: "https://images.unsplash.com/photo-1544568100-847a948585b9?w=400",
  },
  {
    id: "beach-vacation",
    name: "Beach Vacation",
    description: "Tropical beach paradise",
    prompt: "Tropical beach portrait of a pet, wearing sunglasses and Hawaiian shirt, palm trees and ocean, sunset colors, vacation vibes, relaxed happy expression",
    category: "seasonal",
    preview: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
  },
  {
    id: "spring-garden",
    name: "Spring Garden",
    description: "Beautiful spring flower garden",
    prompt: "Spring garden portrait of a pet surrounded by blooming flowers, butterflies, soft pastel colors, golden hour lighting, fresh and joyful atmosphere",
    category: "seasonal",
    preview: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=400",
  },
  {
    id: "autumn-harvest",
    name: "Autumn Harvest",
    description: "Fall foliage and pumpkins",
    prompt: "Autumn portrait of a pet, surrounded by colorful fall leaves, pumpkins, harvest corn, warm golden light, cozy fall sweater, rustic farm background",
    category: "seasonal",
    preview: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=400",
  },
  {
    id: "winter-wonderland",
    name: "Winter Wonderland",
    description: "Snowy winter scene",
    prompt: "Winter portrait of a pet in snowy landscape, wearing cozy scarf, snowflakes falling, pine trees, warm breath vapor, magical winter atmosphere",
    category: "seasonal",
    preview: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=400",
  },
  {
    id: "valentines",
    name: "Valentine's Day",
    description: "Romantic hearts and love",
    prompt: "Valentine portrait of a pet, surrounded by red roses and hearts, romantic pink background, cupid wings, love letter, sweet romantic atmosphere",
    category: "seasonal",
    preview: "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=400",
  },
  {
    id: "st-patricks",
    name: "St. Patrick's Day",
    description: "Lucky Irish celebration",
    prompt: "St. Patrick's Day portrait of a pet, wearing green top hat, clover field, pot of gold rainbow, Irish pub background, festive green colors",
    category: "seasonal",
    preview: "https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=400",
  },

  // Professions (8 styles)
  {
    id: "chef",
    name: "Master Chef",
    description: "Culinary genius in the kitchen",
    prompt: "Portrait of a pet as a master chef, wearing chef hat and white coat, professional kitchen background, cooking utensils, gourmet food presentation",
    category: "profession",
    preview: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
  },
  {
    id: "doctor",
    name: "Doctor",
    description: "Medical professional with stethoscope",
    prompt: "Portrait of a pet as a doctor, wearing white lab coat and stethoscope, hospital background, medical equipment, professional caring expression",
    category: "profession",
    preview: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400",
  },
  {
    id: "pilot",
    name: "Airline Pilot",
    description: "Captain of the skies",
    prompt: "Portrait of a pet as airline pilot, wearing captain uniform and aviator sunglasses, cockpit background, confident pose, professional aviation aesthetic",
    category: "profession",
    preview: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400",
  },
  {
    id: "detective",
    name: "Private Detective",
    description: "Noir-style mystery solver",
    prompt: "Film noir portrait of a pet as detective, trench coat and fedora, magnifying glass, rainy city background, black and white with dramatic shadows",
    category: "profession",
    preview: "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400",
  },
  {
    id: "scientist",
    name: "Mad Scientist",
    description: "Genius inventor in the lab",
    prompt: "Portrait of a pet as mad scientist, wild hair, lab coat, bubbling test tubes, laboratory background, colorful chemical reactions, crazy genius expression",
    category: "profession",
    preview: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=400",
  },
  {
    id: "firefighter",
    name: "Firefighter",
    description: "Brave hero saving lives",
    prompt: "Portrait of a pet as firefighter, wearing helmet and gear, fire truck background, heroic pose, dramatic fire scene, brave expression",
    category: "profession",
    preview: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400",
  },
  {
    id: "musician",
    name: "Rock Star",
    description: "Famous musician on stage",
    prompt: "Portrait of a pet as rock star musician, holding electric guitar, concert stage background, spotlights, crowd silhouettes, rock and roll attitude",
    category: "profession",
    preview: "https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=400",
    popular: true,
  },
  {
    id: "ceo",
    name: "CEO Boss",
    description: "Powerful business executive",
    prompt: "Portrait of a pet as CEO, wearing expensive suit and tie, corner office background, city skyline view, power pose, luxury business aesthetic",
    category: "profession",
    preview: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
  },

  // Sports (6 styles)
  {
    id: "soccer-player",
    name: "Soccer Champion",
    description: "World cup winning player",
    prompt: "Portrait of a pet as soccer player, wearing team jersey, holding trophy, stadium background, confetti celebration, championship victory moment",
    category: "sports",
    preview: "https://images.unsplash.com/photo-1534361960057-19889db9621e?w=400",
  },
  {
    id: "basketball",
    name: "Basketball Star",
    description: "NBA style basketball player",
    prompt: "Portrait of a pet as basketball player, slam dunk pose, basketball court background, NBA style jersey, dynamic action shot",
    category: "sports",
    preview: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400",
  },
  {
    id: "tennis",
    name: "Tennis Pro",
    description: "Grand Slam tennis champion",
    prompt: "Portrait of a pet as tennis player, holding racket, Wimbledon grass court background, white tennis outfit, athletic pose, championship match",
    category: "sports",
    preview: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
  },
  {
    id: "boxer",
    name: "Boxing Champion",
    description: "Heavyweight boxing legend",
    prompt: "Portrait of a pet as boxer, wearing boxing gloves and robe, championship belt, boxing ring background, dramatic lighting, victorious pose",
    category: "sports",
    preview: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400",
  },
  {
    id: "surfer",
    name: "Pro Surfer",
    description: "Catching the perfect wave",
    prompt: "Portrait of a pet as surfer, riding surfboard on big wave, tropical beach background, sunset colors, dynamic action shot, surf culture aesthetic",
    category: "sports",
    preview: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400",
  },
  {
    id: "yoga",
    name: "Yoga Master",
    description: "Zen meditation guru",
    prompt: "Portrait of a pet as yoga master, meditation pose, peaceful zen garden background, incense smoke, soft morning light, serene expression",
    category: "sports",
    preview: "https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400",
  },

  // Cultural (6 styles)
  {
    id: "samurai",
    name: "Samurai Warrior",
    description: "Japanese feudal warrior",
    prompt: "Portrait of a pet as samurai, traditional armor and katana, cherry blossom garden, Japanese temple background, honorable warrior pose",
    category: "cultural",
    preview: "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=400",
    popular: true,
  },
  {
    id: "pharaoh",
    name: "Egyptian Pharaoh",
    description: "Ancient Egyptian royalty",
    prompt: "Portrait of a pet as Egyptian pharaoh, golden headdress and jewelry, pyramid and sphinx background, hieroglyphics, ancient Egypt aesthetic",
    category: "cultural",
    preview: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400",
  },
  {
    id: "geisha",
    name: "Geisha",
    description: "Traditional Japanese elegance",
    prompt: "Portrait of a pet as geisha, elaborate kimono and hair ornaments, traditional Japanese room, paper screens, elegant and refined aesthetic",
    category: "cultural",
    preview: "https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=400",
  },
  {
    id: "bollywood",
    name: "Bollywood Star",
    description: "Glamorous Indian cinema style",
    prompt: "Portrait of a pet as Bollywood star, colorful traditional Indian costume, ornate jewelry, elaborate stage background, dance pose, vibrant colors",
    category: "cultural",
    preview: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
  },
  {
    id: "aztec-warrior",
    name: "Aztec Warrior",
    description: "Ancient Mesoamerican fighter",
    prompt: "Portrait of a pet as Aztec warrior, feathered headdress and shield, ancient temple pyramid background, ceremonial costume, powerful stance",
    category: "cultural",
    preview: "https://images.unsplash.com/photo-1534361960057-19889db9621e?w=400",
  },
  {
    id: "scottish-highlander",
    name: "Scottish Highlander",
    description: "Traditional Scottish warrior",
    prompt: "Portrait of a pet as Scottish highlander, tartan kilt and sporran, bagpipes, misty Scottish highlands background, castle in distance",
    category: "cultural",
    preview: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400",
  },
];

export const petTypes = [
  { id: "dog", name: "Dog", emoji: "🐕" },
  { id: "cat", name: "Cat", emoji: "🐱" },
  { id: "bird", name: "Bird", emoji: "🐦" },
  { id: "rabbit", name: "Rabbit", emoji: "🐰" },
  { id: "hamster", name: "Hamster", emoji: "🐹" },
  { id: "fish", name: "Fish", emoji: "🐠" },
  { id: "reptile", name: "Reptile", emoji: "🦎" },
  { id: "horse", name: "Horse", emoji: "🐴" },
  { id: "other", name: "Other", emoji: "🐾" },
];

export const backgroundOptions = [
  { id: "style-default", name: "Style Default", description: "Use the style's default background" },
  { id: "studio", name: "Studio", description: "Clean professional studio background" },
  { id: "nature", name: "Nature", description: "Beautiful outdoor nature scene" },
  { id: "home", name: "Home", description: "Cozy indoor home setting" },
  { id: "fantasy", name: "Fantasy", description: "Magical fantasy landscape" },
  { id: "transparent", name: "Transparent", description: "No background (PNG)" },
];

// Style transfer styles for the style-transfer tool
export const styleTransferStyles = [
  { id: "van-gogh", name: "Van Gogh", preview: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=400", prompt: "in the style of Vincent van Gogh, swirling brushstrokes, Starry Night aesthetic" },
  { id: "monet", name: "Monet", preview: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400", prompt: "in the style of Claude Monet, impressionist water lilies, soft dappled light" },
  { id: "picasso", name: "Picasso", preview: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=400", prompt: "in the style of Pablo Picasso, cubist fragmented geometry, bold colors" },
  { id: "anime", name: "Anime", preview: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400", prompt: "anime style, Studio Ghibli aesthetic, cel shaded, vibrant colors" },
  { id: "cartoon-3d", name: "3D Cartoon", preview: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400", prompt: "3D animated movie style, Pixar Disney aesthetic, smooth render" },
  { id: "watercolor", name: "Watercolor", preview: "https://images.unsplash.com/photo-1579783928621-7a13d66a62d1?w=400", prompt: "watercolor painting, soft washes, artistic splashes, paper texture" },
  { id: "oil-painting", name: "Oil Painting", preview: "https://images.unsplash.com/photo-1578301978018-3005759f48f7?w=400", prompt: "classical oil painting, rich textures, museum quality, Renaissance style" },
  { id: "pop-art", name: "Pop Art", preview: "https://images.unsplash.com/photo-1561839561-b13bcfe95249?w=400", prompt: "pop art style, Andy Warhol aesthetic, bold colors, halftone dots" },
  { id: "sketch", name: "Pencil Sketch", preview: "https://images.unsplash.com/photo-1572128021190-f02a0e5e57b6?w=400", prompt: "pencil sketch, graphite drawing, detailed shading, paper texture" },
  { id: "cyberpunk", name: "Cyberpunk", preview: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=400", prompt: "cyberpunk style, neon colors, futuristic, sci-fi aesthetic, glowing lights" },
  { id: "renaissance", name: "Renaissance", preview: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=400", prompt: "Renaissance painting style, classical composition, dramatic lighting, old master technique" },
  { id: "comic", name: "Comic Book", preview: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400", prompt: "comic book style, bold outlines, halftone shading, speech bubbles aesthetic" },
];

// Headshot styles
export const headshotStyles = [
  { id: "corporate", name: "Corporate Professional", description: "Classic business headshot", prompt: "professional corporate headshot, business attire, neutral background, studio lighting" },
  { id: "linkedin", name: "LinkedIn Ready", description: "Perfect for LinkedIn profile", prompt: "linkedin profile photo, friendly professional smile, soft lighting, clean background" },
  { id: "creative", name: "Creative Professional", description: "Modern artistic headshot", prompt: "creative professional headshot, artistic lighting, modern background, stylish appearance" },
  { id: "executive", name: "Executive Portrait", description: "C-suite level portrait", prompt: "executive portrait, power pose, luxury office background, confident expression" },
  { id: "startup", name: "Startup Founder", description: "Modern tech industry style", prompt: "startup founder headshot, casual but professional, modern office, approachable" },
  { id: "actor", name: "Actor Headshot", description: "Hollywood casting style", prompt: "actor headshot, dramatic lighting, expressive, cinematic quality" },
];

// Background options for remove-bg tool
export const customBackgrounds = [
  { id: "transparent", name: "Transparent", color: null, preview: "transparent" },
  { id: "white", name: "White", color: "#ffffff", preview: "#ffffff" },
  { id: "black", name: "Black", color: "#000000", preview: "#000000" },
  { id: "blue", name: "Corporate Blue", color: "#1e40af", preview: "#1e40af" },
  { id: "gradient-purple", name: "Purple Gradient", color: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", preview: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)" },
  { id: "gradient-sunset", name: "Sunset", color: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)", preview: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)" },
  { id: "office", name: "Modern Office", color: null, preview: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400", isImage: true },
  { id: "nature", name: "Nature", color: null, preview: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400", isImage: true },
  { id: "city", name: "City Skyline", color: null, preview: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400", isImage: true },
  { id: "studio-gray", name: "Studio Gray", color: "#6b7280", preview: "#6b7280" },
];
